logging:
  level:
    root: debug
    net.ttddyy.dsproxy.listener: debug

spring:
  sleuth:
    jdbc:
      datasource-proxy:
        query:
          enable-logging: true
        slow-query:
          enable-logging: true